{
        "hidebids": false,
        "files": null,
        "attachments": null,
        "bidperiod": 7,
        "currency": {
          "code": "USD",
          "name": "US Dollar",
          "country": "US",
          "sign": "$",
          "exchange_rate": 1,
          "id": 1
        },
        "featured": false,
        "preview_description": "I need some graphic design. Info graphic design 4-5 designs for this project. Must be fluent in Chin",
        "upgrades": {
          "active_prepaid_milestone": null,
          "NDA": false,
          "assisted": null,
          "urgent": false,
          "featured": false,
          "nonpublic": false,
          "fulltime": false,
          "qualified": false,
          "sealed": false,
          "ip_contract": false
        },
        "invited_freelancers": null,
        "id": 14090251,
        "active_prepaid_milestone": null,
        "negotiated": false,
        "title": "Design project",
        "assisted": null,
        "submitdate": 1495318634,
        "nda_signatures": null,
        "project_collaborations": null,
        "nonpublic": false,
        "location": {
          "administrative_area": null,
          "city": null,
          "country": {
            "highres_flag_url": null,
            "code": null,
            "name": null,
            "flag_url_cdn": null,
            "highres_flag_url_cdn": null,
            "flag_url": null
          },
          "vicinity": null,
          "longitude": null,
          "full_address": null,
          "latitude": null
        },
        "recommended_freelancers": null,
        "type": "fixed",
        "hireme": false,
        "owner_id": 24999488,
        "status": "active",
        "jobs": null,
        "description": null,
        "can_post_review": null,
        "deleted": false,
        "qualifications": null,
        "time_free_bids_expire": 1495315033,
        "frontend_project_status": "open",
        "hourly_project_info": null,
        "true_location": null,
        "sub_status": null,
        "time_updated": 1495318634,
        "language": "en",
        "seo_url": "Graphic-Design/Design-project-14090251",
        "urgent": false,
        "user_distance": null,
        "local": false,
        "time_submitted": 1495318634,
        "budget": {
          "currency_id": null,
          "minimum": 30,
          "maximum": 250,
          "project_type": null,
          "name": null
        },
        "negotiated_bid": null,
        "bid_stats": {
          "bid_count": 17,
          "bid_avg": 94.05882352941177
        },
        "hireme_initial_bid": null,
        "from_user_location": null
      },
