function resetDesigner(){
  document.getElementById('front-lineing').style.fill = 'white'
  document.getElementById('frla').style.fill = 'white'
  document.getElementById('flla').style.fill = 'white'
  document.getElementById('fre').style.fill = 'white'
  document.getElementById('fle').style.fill = 'white'
  document.getElementById('frua').style.fill = 'white'
  document.getElementById('flua').style.fill = 'white'
  document.getElementById('frs').style.fill = 'white'
  document.getElementById('fls').style.fill = 'white'
  document.getElementById('frc').style.fill = 'white'
  document.getElementById('flc').style.fill = 'white'
  document.getElementById('frcrotch').style.fill = 'white'
  document.getElementById('flcrotch').style.fill = 'white'
  document.getElementById('frul').style.fill = 'white'
  document.getElementById('flul').style.fill = 'white'
  document.getElementById('frly').style.fill = 'white'
  document.getElementById('flly').style.fill = 'white'
  document.getElementById('frll').style.fill = 'white'
  document.getElementById('flll').style.fill = 'white'
  document.getElementById('faly').style.fill = 'white'
  document.getElementById('fc').style.fill = 'white'
}
